package_name: perl
version: 0.12
license: GPLv2+
authors: [Bohuslav Kabrda <bkabrda@redhat.com>]
homepage: https://github.com/devassistant/dap-perl
summary: Perl assistants
bugreports: https://github.com/devassistant/dap-perl/issues
dependencies:
  - common_args
  - git
  - github
  - vim
description: |
    Kickstarts new Perl projects.
